EveryWorkflowCustomerBundle:
    resource: '@EveryWorkflowCustomerBundle/Resources/config/routes.yaml'

# EveryWorkflowCrmBundle_Controller:
#     resource: "../../Controller/"
#     type: annotation
